### ISSUE TITLE
Specify MESA subsample in README

### ISSUE THREAD

**Issue by yorickvanzweeden** [ojwalch/sleep_classifiers#4]
Dear Olivia,

I have been granted access to the MESA dataset by NSSR. The paper references a subsample of 188 subjects. I was wondering if you could specify which IDs you used for your subsample. This would improve my comparison with your paper, and would save me and potential others time for finding a good subsample. Maybe, you could include these in the README of this project?

https://github.com/ojwalch/sleep_classifiers/blob/375f50e8fc378dc5b32ca67489c7125625da3566/source/mesa/metadata_service.py#L12-L14

https://github.com/ojwalch/sleep_classifiers/blob/375f50e8fc378dc5b32ca67489c7125625da3566/source/mesa/mesa_data_service.py#L9-L17

Kind regards,
Yorick

**Comment by ojwalch** [comment]
Hi Yorick,

I used the first 188 subjects in increasing order of numeric ID. This wasn't for any reason beyond that being the maximum number of files I could keep on my machine without running out of space. I've added this to the README. Since there was no reason beyond practicality for picking that subset, if you have the ability to run more, I'd suggest trying it.

Best,

Olivia
